### ISSUE TITLE
Issue with mockito

### ISSUE THREAD

**Issue by vsumtsov-gh** [techery/janet#57]
I have issue with unit tests.

Code in the **mockedObject**:
```java
bindPipeCached(apiManager.getSignInPipe()).onFail((c, t) -> **loginFailed**());
apiManager.getSignInPipe().send(new MockedToReturnFailCommand());
```

and in tests, verify will fail:
`verify(**mockedObject**, times(1)).**loginFailed**();`
But method loginFailed called OK in the onFail subscriber.

Otherwise, when i call loginFailed, directly in my mocked class. Test passes OK.

I'm using hook for RX:
```java
    static {
        RxJavaPlugins.getInstance().registerSchedulersHook(new RxJavaSchedulersHook() {
            @Override
            public Scheduler getIOScheduler() {
                return Schedulers.immediate();
            }
        });
    }
```

I'm realy can't figure out, what's the reason of the problem.

**Comment by almozavr** [comment]
@vsumtsov-gh By `mockedObject` you mean `spied` object?

**Comment by vsumtsov-gh** [comment]
Yes, i mean spied object.

**Comment by almozavr** [comment]
> But method loginFailed called OK in the onFail subscriber.

Do you mean that you've debugged `onFail` and
`bindPipeCached(apiManager.getSignInPipe()).onFail((c, t) -> **loginFailed**())`;
is still fired but `verify` doesn't take it into account?

**Comment by vsumtsov-gh** [comment]
@almozavr Sorry, I found the reason. That was mistake in my code. Thank you.

**Comment by almozavr** [comment]
U're welcome
